[tool.poetry]
name = "hw-3"
version = "0.0.1"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.11"
numpy = "^2.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
